### ISSUE TITLE
Add exact events ingested count

### ISSUE THREAD

**Issue by atlas-comstock** [talariadb/talaria#128]
Metric `server(table name).ingest.count` is only recorded the events ingested in the batch with same partition key.
https://github.com/talariadb/talaria/blob/cbdbb698406bbe6bf8d29a0f7c6cc7367f2b3243/internal/server/server_ingest.go#L81

I want to add a exact events metric instead count here:

https://github.com/talariadb/talaria/blob/cbdbb698406bbe6bf8d29a0f7c6cc7367f2b3243/internal/server/server_ingest.go#L63

**Comment by atlas-comstock** [comment]
https://github.com/talariadb/talaria/pull/129/files

**Comment by tardunge** [comment]
@atlas-comstock #133 fixes this.
https://github.com/talariadb/talaria/pull/133/files#diff-673e9b930ffcbf9597bcf604f2d4e2f2786960f964d4023b009375fc9c58073eR153
